### ISSUE TITLE
The upload box is not displayed in the foreground after opening the plugin

### ISSUE THREAD

**Issue by ma3252788** [yadenis/DCO-Comment-Attachment#47]
![](https://ypyssl.machunjie.com/machunjie/20210709142758.png)

**Comment by yadenis** [comment]
Hello @ma3252788,

Are you using some custom commenting solution? Can you send a link to the site?

**Comment by ma3252788** [comment]
> Hello @ma3252788,
> 
> Are you using some custom commenting solution? Can you send a link to the site?

Thanks for the reply, I am using the dux theme of WordPress, and the comment code is built in Word Press.

Here is my blog link：

https://www.machunjie.com/linux/978.html

**Comment by yadenis** [comment]
As I understand it, dux is a premium theme. Unfortunately, I won't be able to access it for testing.

But I have some similar support requests, the solution of which was due to the lack of a [comment_form_submit_field](https://github.com/WordPress/WordPress/blob/f545bb3f634c8e949db9051bd88924df592c3337/wp-includes/comment-template.php#L2628) filter in the theme. This filter is used by the plugin [to display the field](https://github.com/yadenis/DCO-Comment-Attachment/blob/master/includes/class-dco-ca.php#L42) for uploading attachments.

Perhaps this is your case. Try contacting your theme support to check it out.

References:
- https://wordpress.org/support/topic/plug-in-doesnt-show-the-add-image-field/
- https://wordpress.org/support/topic/dont-work-on-my-theme-2/
- https://wordpress.org/support/topic/dco-comment-attachment-not-showing-in-comments-area-of-my-website/
- https://wordpress.org/support/topic/plugin-not-working-with-answers-theme/

**Comment by yadenis** [comment]
Closing. Feel free to reopen this issue, or create a new one if you have another questions.
