### ISSUE TITLE
Admin Settings Page Choose File Types

### ISSUE THREAD

**Issue by DuckDivers** [yadenis/DCO-Comment-Attachment#48]
Hi.  

Nice work on this plugin.

I think it would be helpful to add a "Uncheck All" on the choose file type settings page.  Since there's 323 of them. Maybe add a `<button>` under the `show all` toggle, and then simply use:

`jQuery('#column_name input[type="checkbox"]').prop('checked', false);`

Additionally, 

This text "Links to YouTube, Facebook, Twitter and other services inserted in the comment text will be automatically embedded." I think it would be nicer to have as an option that is editable by end users, or at least filterable vs having to use `gettext` hook to update.

I'd be happy to contribute if you'd like.

**Comment by yadenis** [comment]
Hello @DuckDivers
I'm sorry to be late with the reply.

> I think it would be helpful to add a "Uncheck All" on the choose file type settings page

At the moment, you can Check All/Uncheck All by clicking on the type title.
But, apparently, this is not enough user friendly, since such a question has appeared :)

About the button. Perhaps it makes sense to add a checkbox to the type name? Like it is implemented, for example, on the screen for editing posts list.
![2021-09-09_232648](https://user-images.githubusercontent.com/5316579/132757776-28fc5d75-06a4-4257-8e3b-f394abadc429.png)

> at least filterable vs having to use gettext hook to update.

Code:
```
function filter_gettext( $translation, $text, $domain ) {
	if ( $text === 'Links to YouTube, Facebook, Twitter and other services inserted in the comment text will be automatically embedded.' && $domain === 'dco-comment-attachment' ) {
		$translation = 'My text.';
	}

	return $translation;
}

add_filter( 'gettext', 'filter_gettext', 10, 3 );
```
Result:
![2021-09-09_234157](https://user-images.githubusercontent.com/5316579/132759690-5d24c83b-94ba-4f9d-95b8-e167db40fa51.png)

> I think it would be nicer to have as an option that is editable by end users,

I have an issue #22 about it. I plan to place these settings in the customizer in future releases. Feel free to comment 🙌.
